
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloObjis", targetNamespace = "http://simple.demowebservice.objis.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloObjis {


    /**
     * 
     * @param toto
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "reponse", partName = "reponse")
    @Action(input = "http://simple.demowebservice.objis.com/HelloObjis/ditBonjourRequest", output = "http://simple.demowebservice.objis.com/HelloObjis/ditBonjourResponse")
    public String ditBonjour(
        @WebParam(name = "toto", partName = "toto")
        String toto);

}
